# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  build-name: $(Date:yyyyMMdd)$(Rev:.r)

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo 'Compiling get'
          gcc linux/shared-mem/get/get.c -lrt -o linux/shared-mem/get/get
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/linux/shared-mem/get/Dockerfile'
        repository: docker-get
        tags: |
          $(tag)
          $(build-name)
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo 'Saving container'
          docker images
          docker save -o $(Build.ArtifactStagingDirectory)/docker-get-$(build-name).tar docker-get
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
